service: serverless

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

  stage: demo
  region: us-east-1
  
  functions:
    hello:
      handler: handler.generateRandomNumber
      memorySize: 128