---
name: Deploy Serverless Code on Pull Requests

on:
  pull_request:
    branches: [ main ]


jobs:
  deploylambda:
    name: run checks
    runs-on: ubuntu-18.04
  
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js '16'
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          # cache: 'npm'

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y zip unzip
          npm install crypto
          npm install dotenv

      - name: Build Deployment Artifact
        run: |
          zip -r csye6225-lambda-${{ github.run_number }}.zip handler.js 

      - name: Upload Zip to S3
        run: |
            aws s3 cp csye6225-lambda-${{ github.run_number }}.zip s3://${{ secrets.S3_BUCKET }}/csye6225-lambda-${{ github.run_number }}.zip    

      - name: Update Function Code
        run: |
            aws lambda update-function-code --function-name mylambda --s3-bucket ${{ secrets.S3_BUCKET }}

     