---
name: Deploy Serverless Code on Pull Requests

on:
  pull_request:
    branches:
    - main

jobs:
  deploylambda:
    name: run checks
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js '16'
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        # cache: 'npm'

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        # aws-region: ${{ secrets.AWS_REGION }}

    - name: deploy
      run: |
        zip handler.zip handler.js
        aws lambda update-function-code --function-name=test_Service --zip-file=file://handler.zip